mv inst/doc to vignettes/
building vignettes fails with cryptic error messsage

Error in vignette_type(Outfile) :
  Vignette product ‘barebone.tex’ does not have a known filename extension (‘NA’)
ERROR: installing vignettes failed